### ISSUE TITLE
Argument 5 passed to Alchemy\Zippy\Archive\Member::__construct() must be an instance of DateTime

### ISSUE THREAD

**Issue by GoktugOzturk** [alchemy-fr/Zippy#111]
Hi,

I'm trying to open this zip file;
https://github.com/GoktugOzturk/tet-boardsports/archive/master.zip
On my localhost (windows 10 & php 5.6 )
It works fine. 
But on my staging server (Centos & PHP 7.0.6 )
Error occurs:
Argument 5 passed to Alchemy\Zippy\Archive\Member::__construct() must be an instance of DateTime, boolean given, called in /home/project/_shared/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php on line 126

```
$zippy = \Alchemy\Zippy\Zippy::load();
$archive = $zippy->open($tmpFile);
$archive->extract($tmpThemeDir);
if (!file_exists($tmpThemeDir . "/theme/theme.json")) {
    /** @var \Alchemy\Zippy\Archive\MemberInterface[] $zipContents */
    $zipContents = $archive->getMembers();
    foreach ($zipContents as $zipContent) {
        if (substr($zipContent->getLocation(), -16) == "theme/theme.json") {
            $tmpThemeDir .= DIRECTORY_SEPARATOR . str_replace("/theme/theme.json", "", $zipContent->getLocation());
        }
    }
}
```

**Comment by aztech-dev** [comment]
This is an issue with the output format of dates, which can vary dependening on your platform.

See https://github.com/alchemy-fr/Zippy/pull/92 and https://github.com/alchemy-fr/Zippy/issues/86 for more details, you can work around it by specifying the date format used by your platform.

**Comment by GoktugOzturk** [comment]
Our code works on different systems (windows, macos, linux).
Everytime i use Zippy, calling a static parameter with different parameters for each platform doesn't look pretty. 
Should we create an identifier function which tries to identify the operating system and sets default time format for that platform?

I would create this function if needed.

**Comment by aztech-dev** [comment]
For now, I'd rather you place the detection function in your code, not in this library, as there is a full-rewrite and the issue will be resolved. You don't need to call this method everytime you use Zippy, but only once during your application bootstrap, so you can easily detect the platform there and apply the appropriate format.

The library is currently undergoing a full rewrite which should solve those issues, which is why I don't want to add more features to the library for the time being.

**Comment by sannysoft** [comment]
I have php 7.0, mac os
I believe there are not so many datetime formats and most of them system can guess itself the way like:
```
$dateTime = \DateTime::createFromFormat($time,'Y-m-d H:i:s');
if($dateTime==null)
 $dateTime = \DateTime::createFromFormat($time,'H:i Y-m-d');
```

and so on

**Comment by paulredmond** [comment]
This problem had me scratching my head for a while, and I decided to use the `Alchemy\Zippy\Adapter\ZipExtensionAdapter` exclusively to avoid cross-platform `unzip` date issues.

I used an anonymous class as my zip strategy which helped me avoid creating a weird one-off class somewhere in my project.

Here is an example from my [Laravel](https://laravel.com/) service provider (container) for resolving a zippy instance. Hope this helps someone if you are on `>= PHP 7`. If you are not, adapt this to a regular class instead of an anonymous class.

```php
$this->app->singleton('zippy', function () {
    $zippy = Zippy::load();

    $zippy->addStrategy(
        new class($zippy->adapters) extends \Alchemy\Zippy\FileStrategy\ZipFileStrategy
        {
            protected function getServiceNames()
            {
                return [
                    'Alchemy\\Zippy\\Adapter\\ZipExtensionAdapter'
                ];
            }
        }
    );

    return $zippy;
});
```

**Comment by bernard-ng** [comment]
If you are facing this issue you can create a patch

```diff
--- a/vendor/alchemy/zippy/src/Parser/ZipOutputParser.php	2021-04-13 16:13:44.000000000 +0200
+++ b/vendor/alchemy/zippy/src/Parser/ZipOutputParser.php	2022-02-25 22:32:08.116906521 +0200
@@ -64,7 +64,7 @@
 
             if ($mtime === false) {
                 // See https://github.com/alchemy-fr/Zippy/issues/111#issuecomment-251668427
-                $mtime = \DateTime::createFromFormat('H:i Y-m-d', $chunks[2]);
+                $mtime = \DateTime::createFromFormat('m-d-Y H:i', $chunks[2]);
             }
 
             if ($mtime === false) {
```

and apply these changes with  **cweagans/composer-patches**
